---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: demo-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:1.0.18-base-cnb"
  runImage:
    image: "paketobuildpacks/run:1.0.18-base-cnb"
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: demo-store
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/go
    - image: gcr.io/paketo-buildpacks/java
    - image: gcr.io/paketo-buildpacks/nodejs
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: demo-builder
spec:
  tag: ciberkleid/demo-builder
  serviceAccount: kpack-bot
  stack:
    name: demo-stack
    kind: ClusterStack
  store:
    name: demo-store
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/go
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/nodejs
