apiVersion: v1
kind: Secret
metadata:
  name: regcred
  annotations:
    kpack.io/docker: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: ciberkleid
  password: ${DOCKERHUB_PASS}
